#
# Aegis - Config
#

# Boot / Shutdown
boot: 'Enabled %plugin.fullName%'
shutdown: 'Disabled %plugin.fullName%'

# Real Time
real_time:
  enabled: false
  world: 'world'

# MOTD
motd:
  # Your generic MOTD
  message: '&c%plugin.name%'
  # Randomizer (chooses a random MOTD from the list below, overrides generic MOTD)
  whitelist: true
  randomize: false
  messages: []

# Whitelist
whitelist:
  enabled: false
  list: []
  message: '&cWhitelist is currently enabled.'